### ISSUE TITLE
Add location query filter

### ISSUE THREAD

**Issue by filipealva** [edupc/webportal#16]
The clients must be able to query the nearest centers for the given `lat` and `long` parameters

**Comment by ychoy** [comment]
Can you elaborate more? On the mobile app, I understand users would look for nearby centers. What's the use case for librarians to look for nearby centers? Would this be impacted by jurisdiction? e.g. Librarians only see centers within their library municipality? Or all of the centers?

**Comment by filipealva** [comment]
@ychoy sorry, by "the clients" I meant the "mobile apps" that will need to have a query which filters by the end user location.

The librarians will not make use of this location filter.

**Comment by anibalsolon** [comment]
Closed by #35
