### ISSUE TITLE
Report inconsistency/send feedback 

### ISSUE THREAD

**Issue by filipealva** [edupc/webportal#19]
The clients must be able to send a free text report.

It can be:

- General solution feedback (non-related to any center)
- Center feedback (related to a specific center)

**Comment by drgmr** [comment]
@filipealva other than the free text report itself, is any other kind of data required? For example, an e-mail or name?

**Comment by filipealva** [comment]
@edupc for this first version it is not required. Just he free text or the free text + `center.id` for us to know which center the user is talking about
