### ISSUE TITLE
[DISCUSSION] Change Center type name to Facility 

### ISSUE THREAD

**Issue by filipealva** [edupc/webportal#21]
I had a little naming problem on iOS because all the classes who subclass from `UIView` have a property called `center`, so I did a research and it looks like the places we are working with are better known as `disposal facility` or `waste dispostal facility`.

It is not a relevant issue, but what do you guys think about renaming `centert` to `facility` or `disposal facility` on the server side?  cc @edupc @ychoy @anibalsolon

**Comment by drgmr** [comment]
I think either `disposalFacility` or even just `facility` is much more descriptive than `center` and more inclusive. If everyone else agrees I can refactor the code to this.

**Comment by anibalsolon** [comment]
Totally agree on `facility`, it is better than `center` but keeps generic enough in comparison to `disposalFacility`.

**Comment by filipealva** [comment]
nice guys, just let me know when the refactor go up and running so I can also refactor in the iOS app
