### ISSUE TITLE
Authentication and authorization operations

### ISSUE THREAD

**Issue by drgmr** [edupc/webportal#31]
We need to decide how the access to the portal will be handled. At the moment, we have the basis to generate and validate session tokens with any information, alongside a way for any mutation or query handler to check for user information present on the decoded token, but no clear way to create or manage users.

About authorization, my suggestion is having a few roles (e.g. `ADMIN`, `CURATOR`, etc) to associate with users - this "tag" would be added to the token data. Any handler could declare what permissions it requires (for example, `EDIT_FACILITY`) and, before executing it, the server would be able to use this information to deny or allow the execution (with a shared utility function, mapping `ADMIN` and `EDIT_USER` to `true`, for example).

As for authentication, we could have a few default users with permission to create and manage other users or some kind of control over who can request access. Any ideas @anibalsolon @filipealva @lucasmontano @ychoy @caravansteve?

**Comment by anibalsolon** [comment]
Developed on https://github.com/descartae/server .
