### ISSUE TITLE
Inconsistent reference to webpack build directory in server npm scripts

### ISSUE THREAD

**Issue by caravansteve** [edupc/webportal#6]
The npm "start" and "clean" scripts in the server project currently fail, since they reference a build directory called ".build" (with a dot), but the webpack config file uses "build" (without a dot) as the output dir. Assuming we should change ".build" to "build" in the npm scripts, but wasn't sure if you had actually intended to use ".build". Not a big deal, but thought I'd raise the issue :)

**Comment by anibalsolon** [comment]
Thanks @caravansteve ! We will look into it.
